{% set name = "rainbowlog" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rainbowlog-{{ version }}.tar.gz
  sha256: 26b7d8d8560198826bf5bd9af015fe2995233955458b3626e045802589402b6f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core >=1.0.0
  run:
    - constyle >=1.0.2
    - importlib-metadata >=4.11
    - python >={{ python_min }}

test:
  imports:
    - rainbowlog
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/abrahammurciano/rainbowlog
  summary: Format your python logs with colours based on the log levels.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - abrahammurciano
